##################### Style ##################################
Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  EnforcedStyle: compact

Style/Encoding:
  EnforcedStyle: when_needed

Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Description: "Keeps track of empty lines around class bodies."
  EnforcedStyle: empty_lines

Style/RegexpLiteral:
  Description: 'Use / or %r around regular expressions.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-r'
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SignalException:
  Description: 'Checks for proper usage of fail and raise.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#prefer-raise-over-fail'
  EnforcedStyle: only_raise

Style/CaseIndentation:
  Description: 'Indentation of when in a case/when/[else/]end.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#indent-when-to-case'
  EnforcedStyle: case
  IndentOneStep: true

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

##################### Metrics ##################################
Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Max: 100
